FROM greenlizard/base

MAINTAINER GreenLizard Labs <gabriel@greenlizard.com.br>

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN

RUN mvn

